// Starting catalogue for Afro & Sizy.
// Prices are in Ghana cedis and are PLACEHOLDERS -- edit them in Setup > Services.
// duration is in minutes and is used to size appointment slots.

export const CATEGORIES = [
  'Braids',
  'Locs',
  'Nails',
  'Pedicure & Manicure',
  'Lashes',
  'Brows',
  'Wigs & Installation',
  'Styling',
  'Waxing',
  'Barbering',
];

export const SERVICES = [
  // category, name, price (GHS), duration (min)
  ['Braids', 'Knotless Braids (Small)', 400, 300],
  ['Braids', 'Knotless Braids (Medium)', 300, 240],
  ['Braids', 'Knotless Braids (Large)', 220, 180],
  ['Braids', 'Box Braids', 250, 240],
  ['Braids', 'Ghana Weaving', 150, 120],
  ['Braids', 'Cornrows', 120, 90],
  ['Braids', 'Twists (Marley / Passion)', 250, 210],
  ['Braids', 'Faux Locs', 350, 270],
  ['Braids', 'Kids Braids', 120, 120],
  ['Braids', 'Braids Take-Down', 80, 60],

  ['Locs', 'Starter Locs', 300, 180],
  ['Locs', 'Loc Retwist', 150, 90],
  ['Locs', 'Loc Retwist + Style', 220, 150],
  ['Locs', 'Loc Styling', 120, 60],
  ['Locs', 'Loc Extensions', 800, 360],
  ['Locs', 'Loc Repair', 200, 120],
  ['Locs', 'Loc Wash & Treatment', 100, 60],
  ['Locs', 'Interlocking', 250, 150],

  ['Nails', 'Gel Polish (Hands)', 80, 45],
  ['Nails', 'Gel Polish (Toes)', 80, 45],
  ['Nails', 'Acrylic Full Set', 250, 120],
  ['Nails', 'Acrylic Refill', 150, 90],
  ['Nails', 'Nail Extension (Tips)', 200, 105],
  ['Nails', 'Nail Art (per nail)', 15, 10],
  ['Nails', 'Soak-off / Removal', 50, 30],
  ['Nails', 'Nail Repair (per nail)', 20, 15],

  ['Pedicure & Manicure', 'Classic Manicure', 60, 40],
  ['Pedicure & Manicure', 'Spa Manicure', 100, 60],
  ['Pedicure & Manicure', 'Classic Pedicure', 80, 50],
  ['Pedicure & Manicure', 'Spa Pedicure', 130, 75],
  ['Pedicure & Manicure', 'Pedicure + Manicure Combo', 180, 105],
  ['Pedicure & Manicure', 'Paraffin Treatment', 90, 40],
  ['Pedicure & Manicure', 'Callus Treatment', 70, 30],

  ['Lashes', 'Classic Lash Extensions', 150, 90],
  ['Lashes', 'Hybrid Lashes', 200, 105],
  ['Lashes', 'Volume Lashes', 250, 120],
  ['Lashes', 'Mega Volume Lashes', 300, 135],
  ['Lashes', 'Lash Refill', 100, 60],
  ['Lashes', 'Lash Removal', 40, 30],
  ['Lashes', 'Lash Lift & Tint', 180, 75],
  ['Lashes', 'Strip Lashes', 30, 20],

  ['Brows', 'Microblading', 900, 150],
  ['Brows', 'Ombre / Powder Brows', 1000, 165],
  ['Brows', 'Combo Brows', 1200, 180],
  ['Brows', 'Brow Touch-up', 400, 90],
  ['Brows', 'Brow Shaping', 40, 20],
  ['Brows', 'Brow Tint', 60, 30],

  ['Wigs & Installation', 'Frontal Installation', 250, 120],
  ['Wigs & Installation', 'Closure Installation', 200, 100],
  ['Wigs & Installation', 'Glueless Installation', 150, 60],
  ['Wigs & Installation', 'Frontal Customization', 200, 90],
  ['Wigs & Installation', 'Wig Making (Machine)', 250, 150],
  ['Wigs & Installation', 'Wig Making (Hand-stitched)', 400, 300],
  ['Wigs & Installation', 'Wig Revamping', 200, 120],
  ['Wigs & Installation', 'Wig Wash & Style', 120, 60],
  ['Wigs & Installation', 'Wig Coloring', 300, 150],
  ['Wigs & Installation', 'Ponytail Installation', 120, 60],

  ['Styling', 'Tonging / Curling', 80, 45],
  ['Styling', 'Waves', 60, 40],
  ['Styling', 'Blow Dry & Style', 60, 40],
  ['Styling', 'Wash & Set', 70, 50],
  ['Styling', 'Silk Press', 150, 90],
  ['Styling', 'Deep Conditioning Treatment', 100, 45],
  ['Styling', 'Relaxer / Retouch', 150, 90],
  ['Styling', 'Hair Coloring', 250, 120],
  ['Styling', 'Revamping', 150, 90],
  ['Styling', 'Kids Styling', 50, 40],

  ['Waxing', 'Eyebrow Wax', 30, 15],
  ['Waxing', 'Upper Lip Wax', 25, 10],
  ['Waxing', 'Underarm Wax', 60, 20],
  ['Waxing', 'Half Leg Wax', 100, 30],
  ['Waxing', 'Full Leg Wax', 160, 50],
  ['Waxing', 'Bikini Wax', 150, 30],
  ['Waxing', 'Brazilian Wax', 220, 45],
  ['Waxing', 'Back / Chest Wax', 150, 40],
  ['Waxing', 'Full Body Wax', 500, 120],

  ['Barbering', "Men's Haircut", 30, 30],
  ['Barbering', 'Haircut + Beard Trim', 45, 45],
  ['Barbering', 'Beard Trim', 20, 20],
  ['Barbering', 'Kids Haircut', 25, 25],
  ['Barbering', 'Line-up / Shape-up', 15, 15],
  ['Barbering', 'Hair Dye (Men)', 60, 45],
];

export const DEFAULT_SETTINGS = {
  shop_name: 'Afro & Sizy',
  shop_tagline: 'Barbering · Afro & Dreadlocks · Pedicure',
  shop_phone: '0554 143 335',
  shop_address: '',
  currency_symbol: '₵',
  receipt_footer: 'Thank you for choosing Afro & Sizy!',
  brand_color: '#b8283f',
  logo_data: '',
  default_commission: '40',
  loyalty_enabled: '1',
  points_per_cedi: '1',
  points_per_cedi_redeem: '20',
  open_hour: '8',
  close_hour: '20',
  app_pin: '',
};
